services:
  readable:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NO_SANDBOX=1
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
