services:
  readable:
    build: .
    restart: unless-stopped
    container_name: readable
    ports:
      - "6811:8080"
    env_file:
      - .env
    environment:
      - NO_SANDBOX=1
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${HOME}/volumes/readable/extensions:/app/extensions
    networks:
      - caddy-network

networks:
  caddy-network:
    name: caddy-network
